### ISSUE TITLE
Не работает cron.php, если его запускать из консоли.

### ISSUE THREAD

**Issue by kosenka** [novostrim/watcher4site#1]
Не работает cron.php, если его запускать из консоли.
Ошибка:
PHP Warning:  require_once(../lib/ajax_common.php): failed to open stream: No such file or directory in /public_html/watcher4site/api/cron.php on line 8

**Comment by gentee** [comment]
Внесли изменения в cron.php. Попробуйте сейчас.

**Comment by kosenka** [comment]
Не работает.

PHP Warning:  require_once(../app.inc.php): failed to open stream: No such file or directory in /public_html/watcher4site/lib/ajax_common.php on line 9

**Comment by gentee** [comment]
Исправили и ajax_common тоже.

**Comment by kosenka** [comment]
Еще ошибка:
/public_html/watcher4site/api/cron.php
1=3=1PHP Warning:  require_once(../lib/mail.php): failed to open stream: No such file or directory in /public_html/watcher4site/api/cron.php on line 50
PHP Fatal error:  require_once(): Failed opening required '../lib/mail.php' (include_path='.:/usr/local/lib/php') in /public_html/watcher4site/api/cron.php on line 50

**Comment by gentee** [comment]
Исправили.

**Comment by kosenka** [comment]
Спасибо. Работает.
