### ISSUE TITLE
Вынести настройки в конфиг.

### ISSUE THREAD

**Issue by UksusoFF** [novostrim/watcher4site#10]
Можно ли вынести настройки в конфиг файл? Особенно интересует игнорируемые пути.
Добавил путь в игнорируемые пути, а отчеты из этой папки идут и идут.
При больших объемах как я понимаю настройки не перечитываются пока не закончится проверка? 
Или добавить возможность остановить и запустить проверку заново...

**Comment by gentee** [comment]
Когда у вас идет проверка, то в Панели управлении в статусе Состояние есть ссылка Прервать, по ней делается остановка проверки.
Если вы меняете Настройки и нажимаете Начать проверку, то проверка начинается уже с новыми настройками. Если у вас пути не игнорируются, то вернее всего какая-то ошибка в указании этих папок. Можете в качестве примера привести что там указано?

**Comment by UksusoFF** [comment]
Сам виноват, нашел ошибку :)
