### ISSUE TITLE
Уход от хранения конфигов в mysql

### ISSUE THREAD

**Issue by kosenka** [novostrim/watcher4site#2]
Было бы здорово, сделать хранение конфигов и прочей конфигурационной информации не в mysql, а в простых файлах...

**Comment by gentee** [comment]
Так как файлов может быть очень много, то для быстрого получения и изменения информации был выбран MySQL. 
Данные по коннекту к базе данных хранятся в conf.inc.php, который создается при установке системы. Остальные настройки хранятся в MySQL по историческим причинам, так как очень много взято из другой open source системы, которую мы делаем. 
Теоретически можно полностью избавится от MySQL, но на данный момент практического смысла для нас нет.

**Comment by kosenka** [comment]
Ну да, согласен.
