### ISSUE TITLE
Пожелание - когда отсылается email об измененных файлах...

### ISSUE THREAD

**Issue by kosenka** [novostrim/watcher4site#3]
Пожелание - когда отсылается email об измененных файлах, то включать в этот email список этих самых измененных файлов.

**Comment by gentee** [comment]
Мы внесли изменения. Сейчас если изменений меньше 20, то будет отправляться весь список измененных файлов. Если изменений больше, то будет указываться просто количество, сколько добавлено, изменено, удалено.
Изменилось несколько файлов, поэтому минимум нужно обновлять еще api/report.php и lib/ajax_common.php.

**Comment by kosenka** [comment]
Здорово. Спасибо.
