### ISSUE TITLE
Сделать возможность исключения из проверки конкретные файлы

### ISSUE THREAD

**Issue by nynax** [novostrim/watcher4site#5]
Сейчас, можно исключить расширения и директории. А как быть если нужно исключить только один файл?
Поможете ? :)

**Comment by gentee** [comment]
Постараемся за ближайшие дни добавить возможность исключения файлов.

**Comment by gentee** [comment]
Добавили такую возможность. Сейчас вместе с расширениями можно указывать и имена файлов (можно использовать маски).

**Comment by nynax** [comment]
Спасибо большое!
