### ISSUE TITLE
Не устанавливается на хостинг где БД отличная от localhost

### ISSUE THREAD

**Issue by nynax** [novostrim/watcher4site#6]
Здравствуйте!
По старой просьбе, вы сделали поле для ввода отличного от localhost имени DB сервера.
Но, во время установки, выдается сообщение:
Невозможно соединиться с базой данных. Проверьте правильность всех параметров.

Какую дополнительную информацию вам присалать для дебага ?

**Comment by gentee** [comment]
А так-то заходите с такими параметрами? В phpMyAdmin, к примеру?
Если есть возможность, то создайте пустую базу, и скиньте параметры доступа на novostrim @ mail.ru.

**Comment by gentee** [comment]
Я исправил эту ошибку в ajax/install.php. Попробуйте сейчас.

**Comment by nynax** [comment]
Спасибо большое! Все работает!
