### ISSUE TITLE
Не работает при отсутствии доступа в директорию

### ISSUE THREAD

**Issue by nynax** [novostrim/watcher4site#7]
Взломали сайт и изменили права доступа на папку, после этого, watcher4site перестал выполнять свою основную функцию. Подвёл :(

[u200910@dbe390 ~]$ /usr/local/bin/php /home/u200910/rosfirm2.ru/www/c45ebc2adca5bd0d37e56d617f5b041a/api/cron.php
PHP Warning:  dir(/home/u200910/rosfirm2.ru/www/wp-content/plugins/wp-polls/images/default): failed to open dir: Permission denied in /home/u200910/rosfirm2.ru/www/c45ebc2adca5bd0d37e56d617f5b041a/api/watcher.php on line 84
PHP Fatal error:  Call to a member function read() on a non-object in /home/u200910/rosfirm2.ru/www/c45ebc2adca5bd0d37e56d617f5b041a/api/watcher.php on line 87
[u200910@dbe390 ~]$ ls -l /home/u200910/rosfirm2.ru/www/wp-content/plugins/wp-polls/images
total 106
d-wx--x--x  3 u200910  u200910  102912 Jan  8  2012 default
drwxr-xr-x  2 u200910  u200910     512 Jun 10 18:28 default_gradient
-rw-r--r--  1 u200910  u200910     771 Jun 10 18:28 loading.gif

Через web не работает тоже!

**Comment by gentee** [comment]
Добавили проверку на возвращаемое значение dir в watcher.php. Сейчас получается, если на директорию будет запрещен доступ, то все файлы в ней будут определены как удаленные и будет предупреждение.

**Comment by nynax** [comment]
Директория ранее не существовала. Ее создал скрипт вредитель.

**Comment by nynax** [comment]
Как отреагирует watcher4site в таком случае?

**Comment by gentee** [comment]
Внес изменения. Сейчас, если у директории убрали права на доступ, то у нее указывается смена прав а все файлы внутри нее показываются как удаленные. Если добавили директорию без прав на доступ, то она будет показываться как новая.

**Comment by nynax** [comment]
А если создадут файл без прав?

**Comment by gentee** [comment]
Такой файл обнаружится.

**Comment by nynax** [comment]
Спасибо!
