### ISSUE TITLE
Ошибки при запуске из консоли

### ISSUE THREAD

**Issue by UksusoFF** [novostrim/watcher4site#9]
root@uksusoff:~# cd /var/www/uksusoff/data/www/w4s.iamdrunk.ru/api
root@uksusoff:/var/www/uksusoff/data/www/w4s.iamdrunk.ru/api# php cron.php
PHP Warning:  require_once(./lib/ajax_common.php): failed to open stream: No such file or directory in /var/www/uksusoff/data/www/w4s.iamdrunk.ru/api/cron.php on line 8
PHP Fatal error:  require_once(): Failed opening required './lib/ajax_common.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/uksusoff/data/www/w4s.iamdrunk.ru/api/cron.php on line 8

Причем раньше то работало, а тут заметил что никакие отчеты не приходят....

**Comment by gentee** [comment]
А какая у вас версия cron.php? В текущей стоит
$ldir = dirname( dirname( $_SERVER['SCRIPT_FILENAME'] ));
require_once $ldir.'/lib/ajax_common.php';

**Comment by UksusoFF** [comment]
Так и есть, перед тем как запостить [скачал](https://github.com/novostrim/watcher4site/archive/master.zip) и залил поверх.

**Comment by gentee** [comment]
А с файлом lib/ajax_common.php ничего не случилось? На месте?
Попробуйте в cron.php явно указать путь
require_once '/var/www/uksusoff/data/www/w4s.iamdrunk.ru/lib/ajax_common.php';
Будет работать или нет.

**Comment by UksusoFF** [comment]
Да, так работает, но потом ругается еще на: 
require_once $dir.'/app.inc.php';
require_once $dir.'/conf.inc.php';
require_once $ldir."/lib/mail.php";
и
PHP Notice:  Undefined index: HTTP_HOST in /var/www/uksusoff/data/www/w4s.iamdrunk.ru/lib/lib.php on line 8
PHP Notice:  Undefined index: SERVER_ADDR in /var/www/uksusoff/data/www/w4s.iamdrunk.ru/lib/lib.php on line 9
Если прописать абсолютные пути, то все ок...

**Comment by gentee** [comment]
Из браузера все работает нормально?
А вы можете вывести print_r( $_SERVER ) и посмотреть какие элементы там есть. Похоже что при запуcке по крону массив $_SERVER какой-то усеченный.

**Comment by UksusoFF** [comment]
Из браузера вроде ок.

Array
(
    [TERM] => xterm
    [SHELL] => /bin/bash
    [SSH_CLIENT] =>  
    [SSH_TTY] => /dev/pts/0
    [USER] => root
    [MAIL] => /var/mail/root
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [PWD] => /var/www/uksusoff/data/www/w4s.iamdrunk.ru/api
    [SHLVL] => 1
    [HOME] => /root
    [LOGNAME] => root
    [SSH_CONNECTION] =>  
    [_] => /usr/bin/php
    [OLDPWD] => /root
    [PHP_SELF] => cron.php
    [SCRIPT_NAME] => cron.php
    [SCRIPT_FILENAME] => cron.php
    [PATH_TRANSLATED] => cron.php
    [DOCUMENT_ROOT] => 
    [REQUEST_TIME_FLOAT] => 1406807298.9584
    [REQUEST_TIME] => 1406807298
    [argv] => Array
        (
            [0] => cron.php
        )
    [argc] => 1
)
Это не по крону, через SSH.

**Comment by gentee** [comment]
Я обновил файлы cron.php и ajax_common.php. Попробуйте сейчас.

**Comment by UksusoFF** [comment]
Нотайсы остались, остальное работает, спасибо.

**Comment by gentee** [comment]
Обновил lib/lib.php.

**Comment by UksusoFF** [comment]
Отлично :)
